### PR TITLE
fix poetry install

### PR DESCRIPTION
**Pull request by lk2322**

### CODE REVIEW

**Comment by iburakov** [comment]
@lk2322 sorry for the delay, thanks for noticing and fixing this

**Comment by lk2322** [comment]
@iburakov Docker image still can't build, needs another fix

**Comment by iburakov** [comment]
Builds fine on my machine, weird. 

I think, I'll just add a CI action later today to build/push the image to the GitHub Container Registry, so it's easier for everyone to get this thing running.

**Comment by lk2322** [comment]
Hmm, I had some errors while building uwsgi. I'll try to build it again later

**Comment by iburakov** [comment]
@lk2322 good news, I've had some time to work on this and now you don't have to build the image at all! Check the [updated readme](https://github.com/iburakov/my-itmo-ru-to-ical/). PE lessons were added as well.

Feedback is appreciated, because actually I've graduated and can't test it myself :)

**Comment by lk2322** [comment]
@iburakov But pe lessons were already done, weren’t they?
Screenshot_20230923-174053_Календарь~2

**Comment by iburakov** [comment]
Hehe, that's funny. I have no access to test that :)

This is weird because they're requested by a separate endpoint that actually exists:

image

Can you check if you see any duplicates on the latest version?

**Comment by lk2322** [comment]
image
No duplicates

**Comment by iburakov** [comment]
Good, thanks

**Pull request merged**
